name: skybb
version: '${project.version}'
main: my.cufee.skybb.Skybb
api-version: '1.20'

commands:
  sbstart:
    description: Запуск плагина
  startgen:
    description: Запуск игры
  startEvents:
    description: Запускает начало ивентов
